#=======================================================#
#                     gust config file                  #
#  most of this file is comments, which you can delete  #
#=======================================================#

fragment_size: 50
# size of the sliding window genome fragments
# values of 50-300+ should be ok (use your judgement)
# note: bwa isn't good at mapping really long sequences

reference_genome: ""
# name of reference genome in the genomes/ dir

outgroup: ""
# name of the outgroup genome in the genomes/ dir

bwa_parameters: "-a -k 19"
# -a outputs all alignments
# -k 19 is a kmer size of 19

freebayes_parameters: "-C 2 --min-coverage 5 --standard-filter --ploidy 1"
# -C 2 means at least 2 samples need to have alt alleles for a site to be kept
# --min-coverage 5 means at least 5 aligments to score a site
# --standard-filter is to add more stringency
# --ploidy 1 because these are typically haploid assemblies

window_size: 50000
# window size in base pairs for LD pruning snp data
# bigger window = fewer snps

musclev5_parameters: "-replicates 100"
# if runtime is important, you may want to reduce replicates

raxml_model: "GTR+G"
# the phylogenetic model you would like to use

raxml_parameters: "--bs-trees 100 --tree pars{25},rand{25} -brlen scaled"
# --bs-trees 100 is 100 bootstrapped trees
# --tree pars{25},rand{25} is to use 25 parsimonious trees and 25 random trees
# -brlen scaled is the model for branch linkage
